Merge InteratomicBasisPotentials.jl into InteratomicPotentials.jl + Updates from PotentialLearning.jl
cesmix-mit/InteratomicPotentials.jl pull request #50
Opened 2023-11-30 05:41 UTC by emmanuellujan

2023-12-11 23:48 UTC, swyant requested changes

2023-12-11 23:48 UTC, swyant commented on README.md
> +All interatomic potentials listed in this project are subtypes of `ArbitraryPotential`. At this point, as of v2.0, there are two branches of potentials: `EmpiricalPotential` and `MixedPotentials`. A
I would change this to something like "there are three types of potentials currently implemented: `empiricalPotential`, `BasisPotential`, and combination potentials via `MixedPotentials`

2023-12-11 23:48 UTC, swyant commented on src/BasisPotentials/basis_potentials.jl
> +    B = compute_local_descriptors(s, bp.basis, T = T)
You'll have to update these function calls if you get rid of the default casting behavior that was added in

2023-12-11 23:48 UTC, swyant commented on src/BasisPotentials/basis_potentials.jl
As discussed, this needs to be checked very carefully that all prior behavior remains consistent after this refactor.

2023-12-11 23:48 UTC, swyant commented on src/BasisSystems/ACE/ace.jl
> +function ACE(species, body_order, polynomial_degree, wL, csp, r0, rcutoff)
This should be changed to ACE(species, body_order, polynomial_degree, rcutoff; wL=1.5, csp=1.0, r0=2.5)
Actually, I'm not a 100% sure what the default r0 should be, but regardless, I think it should typically not be set.

2023-12-11 23:48 UTC, swyant commented on src/BasisSystems/ACE/ace.jl
Need to remove the default casting behavior with a cast function for the respective descriptors, so that we aren't by default casting on every force/energy call.

2023-12-11 23:48 UTC, swyant commented on src/BasisSystems/SNAP/snap.jl
Need to remove the default casting behavior with a cast function for the respective descriptors, so that we aren't by default casting on every force/energy call.

2023-12-11 23:48 UTC, swyant commented on src/api.jl
> +    compute_local_descriptors(s::AbstractSystem, b::BasisSystem; T = Float64)::Vector{Vector}
Will need to update this once the default casting behavior is removed

2023-12-15 22:58 UTC, emmanuellujan commented on Project.toml
The following code generates a Manifest with 123 dependencies (without considering the extensions)
```
julia --project=./
pkg> add Flux
```

2023-12-21 21:23 UTC, emmanuellujan reviewed
The requested changes were addressed.

2024-01-04 16:04 UTC, swyant approved these changes

2024-01-04 22:38 UTC, emmanuellujan commented on src/BasisPotentials/linear_potential.jl
> +    β0::Vector{T}
Addressed in today's meeting.

2024-01-04 22:38 UTC, merged